### ISSUE TITLE
r57 shell contains phone home backdoors

### ISSUE THREAD

**Issue by Varbaek** [tennc/webshell#19]
webshell/138shell/R/r57 Shell.php.txt

https://github.com/tennc/webshell/blob/master/138shell/R/r57%20Shell.php.txt#L1025

https://github.com/tennc/webshell/blob/master/138shell/R/r57%20Shell.php.txt#L1037

**Comment by tennc** [comment]
https://github.com/tennc/webshell/commit/e0d39713dd0e760775c92e1b0da7ece05b79a4ce

thank you~
