### ISSUE TITLE
Need mysql shell-client for JSP

### ISSUE THREAD

**Issue by shadowfolder** [tennc/webshell#22]
Hi guys! First off, thanks for your page.
I'm looking mysql shell-client for jsp. (I just want browse tables,columns)
I've founded mysql client in one of your shell's but there i can do just simple sql commands, that doesn't enough for me. Any help?

**Comment by tennc** [comment]
hi can you  use other tools ??
like： https://github.com/antoor/antSword/tree/v1.3-dev
i think you will love this it~
