### ISSUE TITLE
PHP7: undefined functions set_magic_quotes_runtime() and ereg()

### ISSUE THREAD

**Issue by rubo77** [tennc/webshell#39]
If you try to run this file on a newer webserver:

webshell/web-malware-collection-13-06-2012/PHP/c99.txt 

You get lots of  php errors

could you update the shell to php7 pls?

**Comment by tennc** [comment]
sorry，i can't rewrite c99.php
You can use antSword or Behinder or Godzilla, they are good webshel​​l management tools.
you can [readme.md](https://github.com/tennc/webshell#%E9%A1%BA%E4%BE%BF%E5%9C%A8%E6%8E%A8%E4%B8%80%E6%B3%A2%E7%BD%91%E7%AB%99%E7%AE%A1%E7%90%86%E5%B7%A5%E5%85%B7)
