### ISSUE TITLE
jsp大马显示乱码，无法执行

### ISSUE THREAD

**Issue by h4m5t** [tennc/webshell#45]

**Comment by tennc** [comment]
can you show me shell file?

**Comment by h4m5t** [comment]
https://github.com/tennc/webshell/blob/9cbc8d5820cd3a83d50fb4ea6bf1c04fd38bd7be/www-7jyewu-cn/%E9%9D%9E%E5%B8%B8%E7%89%9B%E9%80%BC%E7%9A%84Jsp%E5%A4%A7%E9%A9%AC.jsp
文件地址：webshell/www-7jyewu-cn/非常牛逼的Jsp大马.jsp

**Comment by tennc** [comment]
> https://github.com/tennc/webshell/blob/9cbc8d5820cd3a83d50fb4ea6bf1c04fd38bd7be/www-7jyewu-cn/%E9%9D%9E%E5%B8%B8%E7%89%9B%E9%80%BC%E7%9A%84Jsp%E5%A4%A7%E9%A9%AC.jsp
> 文件地址：webshell/www-7jyewu-cn/非常牛逼的Jsp大马.jsp

run ok

look image

![github](https://user-images.githubusercontent.com/670357/121542187-839dc180-ca3a-11eb-9e4f-4612db01fae1.png)

**Comment by h4m5t** [comment]
Well, that should be my problem. Thank you for your help!
