### ISSUE TITLE
 Incorrect path handling in upload function

### ISSUE THREAD

**Issue by Jack-khalif** [tennc/webshell#67]
Hello, I'm reporting an issue with the file upload functionality in the 'webshell' project.

Steps to Reproduce:

Log in to the webshell application.
Navigate to the file upload section.
Attempt to upload a file located at C:\Users\myuser\Documents\example.txt.
Expected Behavior:
The file should be uploaded successfully, and the full path C:\Users\myuser\Documents\example.txt should be preserved in the webshell interface.

Actual Behavior:
When attempting to upload the file, the application appears to strip the full path and only retain the filename example.txt. This makes it difficult to keep track of the original file location.

Environment:

Operating System: Windows 10
Browser: Google Chrome version 98.0.4758.102
Additional Information:
This issue seems to be related to the way the upload functionality handles file paths. Preserving the full file path would be very helpful for users who need to keep track of the original file locations.

Please let me know if you have any questions or need further information. I'm happy to provide more details to help resolve this problem.

**Comment by tennc** [comment]
sorry i don't know,can you search on youtube ?
