### ISSUE TITLE
question about webshell/caidao-shell/wl168168.php

### ISSUE THREAD

**Issue by dezon** [tennc/webshell#7]
wl168168.php is a webshell?
i have never know about it.
can you give me a link about it? 3q.

**Comment by tennc** [comment]
wl168168.php  is a caidao.exe (a webshell tools) web client
caidao.exe  a  web manage tools 
[pic](https://www.fireeye.com/content/dam/legacy/blog/2013/08/image005.png)

**Comment by tennc** [comment]
[fireeye about caidao.exe  some paper ](https://www.fireeye.com/blog/threat-research/2013/08/breaking-down-the-china-chopper-web-shell-part-i.html)

**Comment by dezon** [comment]
but it cann't work , my php version is 5.5.26

**Comment by tennc** [comment]
I test it on  local machine  is running error
so  you are right

**Comment by tennc** [comment]
you look here http://drops.wooyun.org/tips/7279   some php webshell tips

**Comment by dezon** [comment]
ok，i will read it ， 3Q

**Comment by tennc** [comment]
额 还以为你是 国际友人呢。。。。。 :sweat_smile:

**Comment by dezon** [comment]
然而  并不是。。。

**Comment by hackroad** [comment]
楼上对话瞎了我的氪金眼。。。

**Comment by a5216652166** [comment]
wo shi zhongguo de？nimen ne？

**Comment by 2947721120** [comment]
现在在哪里还能下载到没有后门的过狗菜刀呢? 找了几天...全是带后门的木马

**Comment by insafe** [comment]
自己写一个


2016-12-18 19:08 GMT+08:00 炎木 <notifications@github.com>:
